from list_adt import UnorderedList, OrderedList, TriUnorderedList

def test_operations():
    # mylist = UnorderedList()
    mylist = TriUnorderedList()
    mylist.insert(0, 1)
    mylist.add(31)
    mylist.add(77)
    mylist.add(17)
    mylist.add(93)
    mylist.add(26)
    mylist.add(54)
    mylist.add(54)
    mylist.insert(1, 37)
    print(mylist)
    # print(mylist.slice())
    # print(mylist.slice(0,3))

    print(mylist.pop())
    print(mylist.pop(2))
    print(mylist)
    mylist.append(16)
    mylist.add(54)
    print(mylist.index(54))
    print(mylist.index(93))
    print(mylist)

    print(mylist.size())
    # print(mylist.search(93))
    # print(mylist.search(100))

    mylist.add(100)
    # print(mylist.search(100))
    print(mylist.size())

    mylist.remove(54)
    print(mylist)
    print(mylist.size())
    mylist.remove(93)
    print(mylist)
    print(mylist.size())
    mylist.remove(31)
    print(mylist)
    print(mylist.size())
    # print(mylist.search(93))
    print(mylist)

def test_order_list_operations():
    mylist = OrderedList()
    mylist.add(31)
    mylist.add(77)
    mylist.add(17)
    mylist.add(93)
    mylist.add(26)
    mylist.add(54)
    mylist.add(54)
    print(mylist)

    mylist.pop()
    mylist.pop(2)
    mylist.add(54)
    print(mylist.index(54))
    print(mylist.index(93))
    print(mylist)

    print(mylist.size())
    print(mylist.search(93))
    print(mylist.search(100))

    mylist.add(100)
    print(mylist.search(100))
    print(mylist.size())

    print(mylist)
    print(mylist.size())
    print(mylist)
    print(mylist.size())
    print(mylist)
    print(mylist.size())
    print(mylist.search(93))
    print(mylist)

test_operations()
# test_order_list_operations()